AllCops:
  DisabledByDefault: false
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'

# Layout
Layout/LineLength:
  Max: 120

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

# Style
Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: brackets
  Enabled: true

Style/WordArray:
  EnforcedStyle: brackets
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

# Metrics
Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 8

# Naming
Naming/VariableName:
  EnforcedStyle: snake_case

Naming/MethodName:
  EnforcedStyle: snake_case

# Bundler
Bundler/OrderedGems:
  Enabled: true
