AllCops:
  DisabledByDefault: false
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'

# Layout
Layout/LineLength:
  Max: 120

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

# Style
Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: brackets
  Enabled: true

Style/WordArray:
  EnforcedStyle: brackets
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

# Metric

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Lint/MissingSuper:
  Enabled: false

Naming/MethodName:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

# Naming
Naming/VariableName:
  EnforcedStyle: snake_case

# Bundler
Bundler/OrderedGems:
  Enabled: true
